/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import Database.ConnectionProvider;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class NewProduct extends javax.swing.JFrame {

    /**
     * Creates new form NewProduct
     */
    public NewProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtproductname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtrate = new javax.swing.JTextField();
        txtdescription = new javax.swing.JTextField();
        txtactivate = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/New Product ani.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new product.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 600, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Proudct ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 97, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("100");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 93, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 600, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Product Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 155, -1, -1));

        txtproductname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtproductname.setForeground(new java.awt.Color(153, 153, 153));
        txtproductname.setText("Enter Product Name");
        txtproductname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtproductnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtproductnameFocusLost(evt);
            }
        });
        getContentPane().add(txtproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 152, 200, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Rate");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 199, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Description");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 243, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Activate");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 287, -1, -1));

        txtrate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtrate.setForeground(new java.awt.Color(153, 153, 153));
        txtrate.setText("Enter Rate");
        txtrate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtrateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtrateFocusLost(evt);
            }
        });
        getContentPane().add(txtrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 196, 200, -1));

        txtdescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtdescription.setForeground(new java.awt.Color(153, 153, 153));
        txtdescription.setText("Enter Description");
        txtdescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdescriptionFocusLost(evt);
            }
        });
        getContentPane().add(txtdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 240, 200, -1));

        txtactivate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtactivate.setForeground(new java.awt.Color(153, 153, 153));
        txtactivate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        getContentPane().add(txtactivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 284, 200, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 328, 600, 10));

        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 356, -1, -1));

        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 356, -1, -1));

        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close Jframe.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 356, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtproductnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductnameFocusGained
        // TODO add your handling code here:
        if (txtproductname.getText().equals("Enter Product Name")) {
            txtproductname.setText("");
            txtproductname.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtproductnameFocusGained

    private void txtproductnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductnameFocusLost
        // TODO add your handling code here:
        if (txtproductname.getText().equals("")) {
            txtproductname.setText("Enter Product Name");
            txtproductname.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_txtproductnameFocusLost

    private void txtrateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrateFocusGained
        // TODO add your handling code here:
        if (txtrate.getText().equals("Enter Rate")) {
            txtrate.setText("");
            txtrate.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtrateFocusGained

    private void txtrateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrateFocusLost
        // TODO add your handling code here:
        if (txtrate.getText().equals("")) {
            txtrate.setText("Enter Rate");
            txtrate.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtrateFocusLost

    private void txtdescriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdescriptionFocusGained
        // TODO add your handling code here:
        if (txtdescription.getText().equals("Description")) {
            txtdescription.setText("");
            txtdescription.setForeground(new Color(0, 0, 0));
        }

    }//GEN-LAST:event_txtdescriptionFocusGained

    private void txtdescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdescriptionFocusLost
        // TODO add your handling code here:
        if (txtdescription.getText().equals("")) {
            txtdescription.setText("Description");
            txtdescription.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_txtdescriptionFocusLost

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:

        try {
            Connection Con = ConnectionProvider.getcon();
            Statement Stm = Con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet Rs = Stm.executeQuery("select max(Product_ID) from Product");
            if (Rs.first()) {
                int ID = Rs.getInt(1);
                ID = ID + 1;
                String str = String.valueOf(ID);
                jLabel4.setText(str);
            } else {
                jLabel4.setText("1");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_formComponentShown

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String Product_ID = jLabel4.getText();
        String Product_name = txtproductname.getText();
        String Rate = txtrate.getText();
        String Description = txtdescription.getText();
        String Activate = (String) txtactivate.getSelectedItem();

        try {
            Connection Con = ConnectionProvider.getcon();
            Statement Stm = Con.createStatement();
            Stm.executeUpdate("insert into Product values('" + Product_ID + "','" + Product_name + "','" + Rate + "','" + Description + "','" + Activate + "')");
            JOptionPane.showMessageDialog(null, "Successfully Save");
            setVisible(false);
            new NewProduct().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Product is Already Exist");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new NewProduct().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> txtactivate;
    private javax.swing.JTextField txtdescription;
    private javax.swing.JTextField txtproductname;
    private javax.swing.JTextField txtrate;
    // End of variables declaration//GEN-END:variables
}
